#################################################################################
#                          Config Files for Python                              #
#################################################################################
vehicle:
  size:
    width: 0.2
    height: 0.2
data: 
  cam_dir: /home/zonlin/IPP_WorkSpace/ROS_WS/site_ws/src/site_model/camera_data/
  rad_dir: /home/zonlin/IPP_WorkSpace/ROS_WS/site_ws/src/site_model/dataset/radar_data/
output:
  RadCamFusion_dir: /home/zonlin/IPP_WorkSpace/ROS_WS/site_ws/src/site_model/output/RadCamFusion/
topic:
  radar_2: /ARS_408_21_2_Topic
  radar_3: /ARS_408_21_3_Topic
calib:
  camera_info_dir: /home/zonlin/IPP_WorkSpace/ROS_WS/site_ws/src/site_model/src/camera_info/
  pole_pose:
    pole2: [-1.59824637808195, -0.790114867663065, 0.461, 1.5707963267949, 0, 0]
  camera_pose:
    camera11: 
    camera12: 
    camera13: 
    camera14: 
    camera2: [0.298406060019312, -0.0608075188884471, 0.460567976723035, 3.14159265358979, 1.5707963267949, -1.5707963267949]
    camera3: 
    camera41: 
    camera42: 
    camera43: 
    camera44: 